# Generated by Django 4.2.16 on 2024-10-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokens",
            name="is_black_listed",
            field=models.BooleanField(default=False),
        ),
    ]
