# Generated by Django 4.2.16 on 2024-10-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_tokens_is_black_listed"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tokens",
            table="tokens",
        ),
    ]
