# Generated by Django 4.2.16 on 2024-10-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_tokens_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tokens",
            old_name="user_id",
            new_name="user",
        ),
    ]
